# Site settings
title: Free time!
email: 
description: Uma reunião de palestras com conteúdos diversos deixando seu conhecimento ainda mais insano.	
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
# Build settings
source:      .
destination: ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
data_dir: ./_data
collections: null
exclude: ["node_modules", "gulpfile.js", "package.json"]
paginate_path: 'page:num'
paginate: 20
gems: [jekyll-paginate]